version: '3'
services:
  db:
    image: mysql:9.0.0
    ports:
    - 33061:33061
    restart: always
    volumes:
    - ./data/conf.d:/etc/mysql/conf.d
    - mysql:/var/lib/mysql
    env_file:
    - .env

  redis:
    image: redis:latest
    ports:
    - 63792:63792
    volumes:
    - redis:/data
    env_file:
    - .env

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 3000:3000
    depends_on:
    - db
    env_file:
    - .env

  webhook:
    build:
      context: .
      dockerfile: ./webhook.dockerfile
    container_name: webhook
    ports:
    - 9902:9902
    expose:
    - "9902"
    volumes:
    - webhook:/var/share/nginx/html

volumes:
  mysql:
  redis:
  webhook:
