version: '3'
services:
  db:
    image: mysql:latest
    ports:
    - 3306:3306
    volumes:
    - ./data/conf.d:/etc/mysql/conf.d
    - mysql:/var/lib/mysql
    env_file:
    - .env
  redis:
    image: redis:latest
    ports:
    - 63792:63792
    volumes:
    - redis:/data
    env_file:
    - .env

volumes:
  mysql:
  redis:
